package ar.noxit.dataaccessobject.hibernate;

import ar.noxit.dataaccessobject.IDao;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import javax.persistence.PersistenceException;
import net.sf.cglib.proxy.MethodInterceptor;
import net.sf.cglib.proxy.MethodProxy;
import org.hibernate.NonUniqueObjectException;
import org.hibernate.ObjectNotFoundException;

/**
 * An Hibernate exception translator implemented using a cglib interceptor
 * 
 * @author Mauro Ciancio
 * 
 */
public class HibernateExceptionTranslatorInterceptor implements MethodInterceptor {

    /**
     * Dao to be wrapped
     */
    private IDao<?, ?> dao;

    /**
     * Creates a new interceptor to wrap the dao argument
     * 
     * @param dao
     *            to be wrapped
     */
    public HibernateExceptionTranslatorInterceptor(IDao<?, ?> dao) {
        if (dao == null) {
            throw new IllegalArgumentException("dao cannot be null");
        }

        this.dao = dao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object intercept(Object obj, Method method, Object[] args, MethodProxy proxy) throws Throwable {
        try {
            return method.invoke(dao, args);
        } catch (InvocationTargetException e) {
            // jpa exception
            Throwable cause = e.getCause();

            if (cause instanceof PersistenceException) {
                try {
                    throw cause.getCause();
                } catch (ObjectNotFoundException ex) {
                    throw new ar.noxit.exceptions.persistence.ObjectNotFoundException("El objeto no se encontr贸", ex);
                } catch (NonUniqueObjectException ex) {
                    throw new ar.noxit.exceptions.persistence.NonUniqueException("Objecto duplicado", e);
                } catch (Exception ex) {
                    throw new ar.noxit.exceptions.persistence.PersistenceException("Excepci贸n irrecuperable", ex);
                }
            }

            throw new ar.noxit.exceptions.persistence.PersistenceException("Excepci贸n irrecuperable", e);
        } catch (Exception ex) {
            // other exception type
            if (!(ex instanceof ar.noxit.exceptions.persistence.PersistenceException)) {
                throw new ar.noxit.exceptions.persistence.PersistenceException("Excepci贸n irrecuperable", ex);
            }
            throw ex;
        }
    }
}
